apiVersion: v1
kind: Secret
metadata:
  name: todo-secret
  namespace: {{ .Values.namespace }}
type: Opaque
stringData:
  POSTGRES_DB: {{ .Values.postgres.database | quote }}
  POSTGRES_USER: {{ .Values.postgres.username | quote }}
  POSTGRES_PASSWORD: {{ .Values.postgres.password | quote }}
  DATABASE_URL: "postgresql+psycopg2://{{ .Values.postgres.username }}:{{ .Values.postgres.password }}@todo-postgres:{{ .Values.postgres.port }}/{{ .Values.postgres.database }}"
  SECRET_KEY: {{ .Values.appSecret.secretKey | quote }}
  ALGORITHM: {{ .Values.appSecret.algorithm | quote }}
  ACCESS_TOKEN_EXPIRE_MINUTES: {{ .Values.appSecret.accessTokenExpireMinutes | quote }}
