namespace: todo-app

frontend:
  image:
    repository: mehedib127/todo-frontend
    tag: "bb6138c36d43686d656794e67292982c1d728550"

  replicas: 2
  port: 80
  apiUrl: /api

  resources:
    requests:
      cpu: 50m
      memory: 64Mi

    limits:
      cpu: 250m
      memory: 128Mi

backend:
  image:
    repository: mehedib127/todo-backend
    tag: "bb6138c36d43686d656794e67292982c1d728550"

  replicas: 2
  port: 8000

  resources:
    requests:
      cpu: 100m
      memory: 128Mi

    limits:
      cpu: 500m
      memory: 512Mi

  hpa:
    enabled: true
    minReplicas: 2
    maxReplicas: 5
    averageUtilization: 70

postgres:
  image: postgres:16-alpine
  port: 5432
  storage: 5Gi
  database: todo_db
  username: todo_user
  password: todo_password

appSecret:
  secretKey: change-this-secret-key-use-a-long-random-value
  algorithm: HS256
  accessTokenExpireMinutes: "60"

ingress:
  enabled: true
  className: traefik
  host: ""

  tls:
    enabled: false
    secretName: todo-tls